# Order Service Configuration
# This file configures the Order Service properties

# Server port configuration
# Using port 8082 to avoid conflicts with other services
server:
  port: 8082

# Spring application name
# This name is used when registering with Eureka Server
spring:
  application:
    name: order-service

# Eureka client configuration
# Specifies how this service registers with Eureka Server
eureka:
  client:
    service-url:
      # URL of the Eureka Server where this service will register
      defaultZone: http://localhost:8761/eureka/
