# Product Service Configuration
# This file configures the Product Service properties

# Server port configuration
# Using port 8081 to avoid conflicts with other services
server:
  port: 8081

# Spring application name
# This name is used when registering with Eureka Server
spring:
  application:
    name: product-service

# Eureka client configuration
# Specifies how this service registers with Eureka Server
eureka:
  client:
    service-url:
      # URL of the Eureka Server where this service will register
      defaultZone: http://localhost:8761/eureka/
